# Generated by Django 5.0.6 on 2026-03-09 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeMultiplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_slug', models.SlugField(max_length=120)),
                ('multiplier', models.PositiveIntegerField(default=1)),
                ('shopping_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multipliers', to='shopping.shoppinglist')),
            ],
            options={
                'unique_together': {('shopping_list', 'recipe_slug')},
            },
        ),
    ]
