# Generated by Django 5.0.6 on 2026-04-18 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipebook',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
