# Generated by Django 5.0.6 on 2026-04-18 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_remove_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipebook',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='recipebook',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
