# Generated by Django 5.0.6 on 2026-02-16 05:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=280)),
                ('serves', models.CharField(max_length=50)),
                ('ingredients', models.JSONField(default=list)),
                ('instructions', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('soup', 'Soup'), ('pasta', 'Pasta'), ('bake', 'Bake'), ('salad', 'Salad'), ('grill', 'Grill'), ('breakfast', 'Breakfast'), ('dessert', 'Dessert'), ('drink', 'Drink'), ('snack', 'Snack'), ('other', 'Other')], max_length=20)),
                ('fork_count', models.PositiveIntegerField(default=0)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL)),
                ('parent_recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forks', to='recipes.recipe')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
