# Generated by Django 5.0.6 on 2026-04-04 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_add_status_and_published_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestKitchenInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invitee', models.ForeignKey(help_text="The user who gains read access to the owner's drafts.", on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_invites_received', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(help_text='The user whose test kitchen is being shared.', on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_invites_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('owner', 'invitee')},
            },
        ),
    ]
