# Generated by Django 5.0.6 on 2026-03-21 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_image_url_db_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('kind', models.CharField(choices=[('cuisine', 'Cuisine'), ('dietary', 'Dietary'), ('ingredient', 'Ingredient'), ('vibe', 'Vibe')], default='vibe', max_length=20)),
            ],
            options={
                'ordering': ['kind', 'name'],
            },
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='recipes.tag'),
        ),
    ]
