# Generated by Django 5.0.6 on 2026-03-21 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_migrate_category_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('sandwich_burger', 'Sandwiches & Burgers'), ('pizza', 'Pizza & Flatbreads'), ('soup', 'Soup & Stews'), ('salad', 'Salads'), ('pasta_noodles', 'Pasta & Noodles'), ('meat_seafood', 'Meat & Seafood'), ('bowl', 'Bowls'), ('casserole_bake', 'Casseroles & Bakes'), ('side_dish', 'Side Dishes'), ('sauce_condiment', 'Sauces & Condiments'), ('breakfast_bakery', 'Breakfast & Bakery'), ('dessert', 'Desserts'), ('drink', 'Drinks'), ('snack_app', 'Snacks & Appetizers'), ('other', 'Other')], max_length=20),
        ),
    ]
