# Generated by Django 5.0.6 on 2026-03-21 19:48

from django.db import migrations
from django.utils.text import slugify


SEED_TAGS = {
    "cuisine": [
        "mediterranean", "mexican", "asian", "american",
        "chinese", "italian", "japanese", "indian",
    ],
    "dietary": ["vegetarian", "vegan", "healthy"],
    "ingredient": ["steak", "seafood", "chicken", "sushi"],
}


def seed_tags_forward(apps, schema_editor):
    Tag = apps.get_model("recipes", "Tag")
    for kind, names in SEED_TAGS.items():
        for name in names:
            Tag.objects.get_or_create(
                name=name,
                defaults={"slug": slugify(name), "kind": kind},
            )


def seed_tags_reverse(apps, schema_editor):
    Tag = apps.get_model("recipes", "Tag")
    all_names = [n for names in SEED_TAGS.values() for n in names]
    Tag.objects.filter(name__in=all_names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_recipe_category'),
    ]

    operations = [
        migrations.RunPython(seed_tags_forward, seed_tags_reverse),
    ]
