# Generated by Django 5.0.6 on 2026-04-04 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_publish_existing_recipes'),
        ('recipes', '0007_seed_tags'),
    ]

    operations = [
    ]
