# Generated by Django 5.0.6 on 2026-04-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_merge_0004_publish_existing_recipes_0007_seed_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='review_round',
            field=models.PositiveIntegerField(default=0, help_text='0 = never submitted. Incremented on each submit-for-review.'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('mod_queue', 'Moderation Queue'), ('revision_requested', 'Revision Requested'), ('published', 'Published')], db_index=True, default='draft', max_length=20),
        ),
    ]
