# Generated by Django 5.0.6 on 2026-04-18 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_onevote_per_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipereview',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='1-5 spoon rating. Only used for published recipes.', null=True),
        ),
    ]
